version: '3.4'

services:
  db:
    build:
      context: ./db
      network: host
      dockerfile: Dockerfile
    ports:
      - '192.168.0.184:5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nosqldb:
    build:
      context: ./nosql
    deploy:
      replicas: 1
    ports:
      - '192.168.0.184:8091:8091'
      - '192.168.0.184:8092:8092'
      - '192.168.0.184:8093:8093'
      - '192.168.0.184:8094:8094'
      - '192.168.0.184:11210:11210'
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET=demobucket
      - COUCHBASE_RBAC_USERNAME=demobucket
      - COUCHBASE_RBAC_PASSWORD=password
      - COUCHBASE_RBAC_NAME=admin
      - CLUSTER_NAME=demo-cluster
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - '192.168.0.184:8080:8080'
    restart: always
    depends_on: 
      - db 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.0.184:5432/hotel
      SPRING_DATASOURCE_USERNAME: hotel
      SPRING_DATASOURCE_PASSWORD: hotel
volumes:
  db-data: